import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { isAdminAuthenticated } from "@/lib/admin/verify";
import { generateTrackingCode } from "@/lib/trackingCode";
import { getPublishedTerms } from "@/lib/siteContent";

function mapCommission(row:Record<string,unknown>){return {...row,client_email:String(row.client_email||""),client_contact:row.client_contact?String(row.client_contact):null,tiktok_username:row.tiktok_username?String(row.tiktok_username):null,commission_type_label:String(row.commission_type_label||"Comisión"),character_name:String(row.character_name||"Sin título"),reference_urls:Array.isArray(row.reference_urls)?row.reference_urls:[],estimated_price:row.estimated_price==null?null:Number(row.estimated_price),quoted_price:row.quoted_price==null?null:Number(row.quoted_price),paid_amount:Number(row.paid_amount||0),show_in_public_queue:row.show_in_public_queue!==false}}
export async function GET(){if(!(await isAdminAuthenticated()))return NextResponse.json({error:"No autorizado"},{status:401});const{data,error}=await getSupabaseServerClient().from("commissions").select("*").order("created_at",{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({commissions:(data||[]).map(row=>mapCommission(row as Record<string,unknown>))})}
export async function POST(request:NextRequest){if(!(await isAdminAuthenticated()))return NextResponse.json({error:"No autorizado"},{status:401});const body=await request.json().catch(()=>null);if(!body?.client_name?.trim())return NextResponse.json({error:"Escribe el nombre del cliente."},{status:400});const terms=await getPublishedTerms();const payload={tracking_code:generateTrackingCode(),client_name:body.client_name.trim(),client_email:body.client_email?.trim().toLowerCase()||"sin-correo@local.invalid",client_contact:body.client_contact?.trim()||null,tiktok_username:body.tiktok_username?.trim().replace(/^@/,"")||null,commission_type_id:body.commission_type_id||null,commission_type_label:body.commission_type_label?.trim()||"Comisión manual",character_name:body.character_name?.trim()||"Comisión manual",character_description:body.character_description?.trim()||null,reference_urls:Array.isArray(body.reference_urls)?body.reference_urls:String(body.reference_urls||"").split("\n").map((x:string)=>x.trim()).filter(Boolean),pose_description:body.pose_description?.trim()||null,usage_type:body.usage_type==="comercial"?"comercial":"personal",payment_method:body.payment_method?.trim()||"Por definir",additional_details:body.additional_details?.trim()||null,estimated_price:body.estimated_price?Number(body.estimated_price):null,quoted_price:body.quoted_price?Number(body.quoted_price):null,paid_amount:Number(body.paid_amount||0),currency:body.currency||"MXN",deadline:body.deadline||null,priority:body.priority||"normal",source:"admin",platform:body.platform?.trim()||"Directo",show_in_public_queue:body.show_in_public_queue!==false,public_alias:body.public_alias?.trim()||null,terms_accepted:false,terms_version:terms.version,status:"solicitud"};const{data,error}=await getSupabaseServerClient().from("commissions").insert(payload).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({commission:mapCommission(data as Record<string,unknown>)},{status:201})}
