"use client";
import { useEffect,useMemo,useState } from "react";
import { COMMISSION_STAGES,STAGE_LABELS,type Commission } from "@/types/commission";
import CommissionDetailModal from "./CommissionDetailModal";
import NewCommissionModal from "./NewCommissionModal";

export default function AdminBoard(){
  const[items,setItems]=useState<Commission[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Commission|null>(null),[creating,setCreating]=useState(false);
  function fetchCommissions(){fetch("/api/admin/commissions").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.commissions||[]);setError("")}).catch(e=>setError(e.message||"No se pudo cargar.")).finally(()=>setLoading(false))}
  useEffect(()=>{fetchCommissions()},[]);
  const grouped=useMemo(()=>Object.fromEntries(COMMISSION_STAGES.map(stage=>[stage,items.filter(item=>item.status===stage)])) as Record<Commission["status"],Commission[]>,[items]);
  async function move(item:Commission,status:Commission["status"]){const before=item.status;setItems(current=>current.map(x=>x.id===item.id?{...x,status}:x));const r=await fetch(`/api/admin/commissions/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)setItems(current=>current.map(x=>x.id===item.id?{...x,status:before}:x))}
  return <div><div className="board-toolbar"><div><b>{items.length}</b> comisiones registradas</div><button className="btn-primary" onClick={()=>setCreating(true)}>+ Nueva comisión</button></div>{error&&<p className="alert-error">{error}</p>}{loading?<p>Cargando tablero...</p>:<div className="kanban-board">{COMMISSION_STAGES.map(stage=><section className="kanban-column" key={stage}><header><h2>{STAGE_LABELS[stage]}</h2><span>{grouped[stage].length}</span></header><div>{grouped[stage].map(item=><article className="kanban-card" key={item.id}><button className="kanban-open" onClick={()=>setSelected(item)}><small>{item.commission_type_label}</small><h3>{item.character_name}</h3><p>{item.client_name}</p><code>{item.tracking_code}</code><div className="money-line"><span>{item.quoted_price?`${item.currency} ${item.quoted_price.toLocaleString("es-MX")}`:"Sin cotizar"}</span><span>{item.deadline||"Sin fecha"}</span></div></button><select value={item.status} onChange={e=>move(item,e.target.value as Commission["status"])}>{COMMISSION_STAGES.map(option=><option key={option} value={option}>{STAGE_LABELS[option]}</option>)}</select></article>)}{!grouped[stage].length&&<p className="empty-column">Vacío</p>}</div></section>)}</div>}{selected&&<CommissionDetailModal commission={selected} onClose={()=>setSelected(null)} onUpdated={updated=>{setItems(current=>current.map(x=>x.id===updated.id?updated:x));setSelected(updated)}} onDeleted={id=>{setItems(current=>current.filter(x=>x.id!==id));setSelected(null)}}/>}{creating&&<NewCommissionModal onClose={()=>setCreating(false)} onCreated={commission=>{setItems(current=>[commission,...current]);setCreating(false)}}/>}</div>
}
