"use client";
import { useEffect,useState } from "react";
import { COMMISSION_STAGES,STAGE_LABELS,type Commission,type ProgressNote } from "@/types/commission";

export default function CommissionDetailModal({commission,onClose,onUpdated,onDeleted}:{commission:Commission;onClose:()=>void;onUpdated:(value:Commission)=>void;onDeleted:(id:string)=>void}){
  const[draft,setDraft]=useState(commission),[notes,setNotes]=useState<ProgressNote[]>([]),[newNote,setNewNote]=useState(""),[visible,setVisible]=useState(true),[evidence,setEvidence]=useState<string|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetch(`/api/admin/commissions/${commission.id}/notes`).then(r=>r.json()).then(d=>setNotes(d.notes||[]))},[commission.id]);
  const change=(key:keyof Commission,value:unknown)=>setDraft(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setMessage("");const payload={...draft,reference_urls:draft.reference_urls};const r=await fetch(`/api/admin/commissions/${draft.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setSaving(false);if(!r.ok)return setMessage(d.error||"No se pudo guardar.");const updated={...draft,...d.commission,reference_urls:d.commission.reference_urls||draft.reference_urls} as Commission;onUpdated(updated);setMessage("Cambios guardados.")}
  async function addNote(){if(!newNote.trim()&&!evidence)return;const r=await fetch(`/api/admin/commissions/${draft.id}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note:newNote,visible_to_client:visible,image_url:evidence})});const d=await r.json();if(!r.ok)return setMessage(d.error||"No se pudo guardar la nota.");setNotes(current=>[d.note,...current]);setNewNote("");setEvidence(null)}
  async function remove(){if(!confirm("¿Eliminar esta comisión y sus notas?"))return;const r=await fetch(`/api/admin/commissions/${draft.id}`,{method:"DELETE"});if(r.ok)onDeleted(draft.id)}
  function readEvidence(file?:File){if(!file)return setEvidence(null);if(file.size>2*1024*1024)return setMessage("La evidencia no puede superar 2 MB.");const reader=new FileReader();reader.onload=()=>setEvidence(String(reader.result));reader.readAsDataURL(file)}
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="admin-modal wide" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">{draft.tracking_code}</p><h2>{draft.character_name}</h2></div><button onClick={onClose}>✕</button></header><div className="modal-body">
    <div className="form-grid">
      <Field label="Cliente"><input className="input" value={draft.client_name} onChange={e=>change("client_name",e.target.value)}/></Field><Field label="Correo"><input className="input" value={draft.client_email} onChange={e=>change("client_email",e.target.value)}/></Field>
      <Field label="Contacto"><input className="input" value={draft.client_contact||""} onChange={e=>change("client_contact",e.target.value||null)}/></Field><Field label="TikTok"><input className="input" value={draft.tiktok_username||""} onChange={e=>change("tiktok_username",e.target.value||null)}/></Field>
      <Field label="Servicio"><input className="input" value={draft.commission_type_label} onChange={e=>change("commission_type_label",e.target.value)}/></Field><Field label="Título / personaje"><input className="input" value={draft.character_name} onChange={e=>change("character_name",e.target.value)}/></Field>
      <Field label="Etapa"><select className="input" value={draft.status} onChange={e=>change("status",e.target.value)}>{COMMISSION_STAGES.map(stage=><option key={stage} value={stage}>{STAGE_LABELS[stage]}</option>)}</select></Field><Field label="Prioridad"><select className="input" value={draft.priority} onChange={e=>change("priority",e.target.value)}><option value="baja">Baja</option><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></Field>
      <Field label="Precio final"><input className="input" type="number" step="0.01" value={draft.quoted_price??""} onChange={e=>change("quoted_price",e.target.value===""?null:Number(e.target.value))}/></Field><Field label="Pagado"><input className="input" type="number" step="0.01" value={draft.paid_amount} onChange={e=>change("paid_amount",Number(e.target.value))}/></Field>
      <Field label="Fecha límite"><input className="input" type="date" value={draft.deadline||""} onChange={e=>change("deadline",e.target.value||null)}/></Field><Field label="Alias público"><input className="input" value={draft.public_alias||""} onChange={e=>change("public_alias",e.target.value||null)}/></Field>
      <Field label="Descripción" wide><textarea className="input min-h-24" value={draft.character_description||""} onChange={e=>change("character_description",e.target.value||null)}/></Field><Field label="Pose / escena" wide><textarea className="input min-h-20" value={draft.pose_description||""} onChange={e=>change("pose_description",e.target.value||null)}/></Field><Field label="Referencias (una por línea)" wide><textarea className="input min-h-20" value={draft.reference_urls.join("\n")} onChange={e=>change("reference_urls",e.target.value.split("\n").map(x=>x.trim()).filter(Boolean))}/></Field><Field label="Notas internas del encargo" wide><textarea className="input min-h-20" value={draft.additional_details||""} onChange={e=>change("additional_details",e.target.value||null)}/></Field>
    </div><label className="terms-check"><input type="checkbox" checked={draft.show_in_public_queue} onChange={e=>change("show_in_public_queue",e.target.checked)}/><span>Mostrar este pedido en el Kanban público sin datos del cliente.</span></label>
    <div className="modal-save-row">{message&&<p>{message}</p>}<button className="btn-primary" onClick={save} disabled={saving}>{saving?"Guardando...":"Guardar comisión"}</button></div>
    <section className="notes-admin"><h3>Notas de progreso</h3><textarea className="input" placeholder="Actualización para el cliente o nota interna" value={newNote} onChange={e=>setNewNote(e.target.value)}/><input className="input" type="file" accept="image/*" onChange={e=>readEvidence(e.target.files?.[0])}/><div className="note-actions"><label><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Visible para el cliente</label><button className="btn-secondary" onClick={addNote}>Agregar nota</button></div><div className="note-list">{notes.map(note=><article key={note.id}><small>{new Date(note.created_at).toLocaleString("es-MX")} · {note.visible_to_client?"Pública":"Solo admin"}</small><p>{note.note}</p>{note.image_url&&<>
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={note.image_url} alt="Evidencia"/></>}</article>)}</div></section>
    <button className="danger-link" onClick={remove}>Eliminar comisión</button>
  </div></div></div>
}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
