"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect,useState } from "react";

interface Artwork{id:string;title:string;description:string|null;image_url:string;artist_name:string|null;artist_url:string|null;featured:boolean;active:boolean;sort_order:number;tags:string[]}
export default function GalleryAdmin(){const[items,setItems]=useState<Artwork[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);function load(){fetch("/api/admin/portfolio").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.portfolio||[])}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))}useEffect(load,[]);
async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=e.currentTarget;const r=await fetch("/api/admin/portfolio",{method:"POST",body:new FormData(form)});const d=await r.json();setSaving(false);if(!r.ok)return setMessage(d.error||"No se pudo publicar.");setItems(current=>[d.item,...current]);form.reset();setMessage("Dibujo publicado.")}
function change(id:string,key:keyof Artwork,value:unknown){setItems(current=>current.map(item=>item.id===id?{...item,[key]:value}:item))}
async function save(item:Artwork){const r=await fetch(`/api/admin/portfolio/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const d=await r.json();setMessage(r.ok?`«${item.title}» actualizado.`:d.error||"No se pudo guardar.")}
async function remove(item:Artwork){if(!confirm(`¿Eliminar «${item.title}»?`))return;const r=await fetch(`/api/admin/portfolio/${item.id}`,{method:"DELETE"});if(r.ok)setItems(current=>current.filter(x=>x.id!==item.id))}
return <div className="admin-stack">{message&&<p className="admin-message">{message}</p>}<section className="admin-card"><h2>Subir dibujo</h2><form className="form-grid" onSubmit={create}><Field label="Imagen *"><input className="input" type="file" name="file" accept="image/*" required/></Field><Field label="Título *"><input className="input" name="title" required/></Field><Field label="Etiquetas"><input className="input" name="tags" placeholder="Icon, Full color, Piumi"/></Field><Field label="Orden"><input className="input" name="sort_order" type="number" defaultValue="0"/></Field><Field label="Artista"><input className="input" name="artist_name"/></Field><Field label="Enlace del artista"><input className="input" name="artist_url" type="url"/></Field><Field label="Descripción" wide><textarea className="input min-h-24" name="description"/></Field><label className="terms-check"><input type="checkbox" name="featured"/><span>Destacado</span></label><label className="terms-check"><input type="checkbox" name="active" defaultChecked/><span>Visible</span></label><button className="btn-primary wide" disabled={saving}>{saving?"Subiendo...":"Publicar dibujo"}</button></form></section>
<section><div className="admin-section-title"><h2>Dibujos publicados</h2><span>{items.length}</span></div>{loading?<p>Cargando...</p>:<div className="admin-gallery-grid">{items.map(item=><article className="admin-art-card" key={item.id}><img src={item.image_url} alt={item.title}/><div className="admin-art-form"><input className="input" value={item.title} onChange={e=>change(item.id,"title",e.target.value)}/><textarea className="input" value={item.description||""} onChange={e=>change(item.id,"description",e.target.value||null)}/><input className="input" value={item.tags.join(", ")} onChange={e=>change(item.id,"tags",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/><div className="inline-fields"><label><input type="checkbox" checked={item.featured} onChange={e=>change(item.id,"featured",e.target.checked)}/> Destacado</label><label><input type="checkbox" checked={item.active} onChange={e=>change(item.id,"active",e.target.checked)}/> Visible</label></div><div className="card-actions"><button className="btn-primary" onClick={()=>save(item)}>Guardar</button><button className="btn-secondary" onClick={()=>remove(item)}>Eliminar</button></div></div></article>)}</div>}</section></div>}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
